USER = 'postgres'
PASSWORD = '123'
HOST = 'localhost'
PORT = '5432'
DATABASE_NAME = 'iphone' 

BRAND_SCALE = {
    'APPLE IPHONE 6S PLUS': 1,
    'APPLE IPHONE 7 PLUS': 2,
    'APPLE IPHONE 8 PLUS': 3,
    'APPLE IPHONE XR': 4,
    'APPLE IPHONE 11 PRO MAX': 5,
    'APPLE IPHONE 12 MINI': 6,
    'APPLE IPHONE 12 PRO MAX': 7,
    'APPLE IPHONE 13 PRO MAX': 8,
    'APPLE IPHONE 14 PRO MAX': 9,
    'APPLE IPHONE 15 PRO MAX': 10
}

PROCESSOR_SCALE = {
    'APPLE A8': 1,
    'APPLE A10 FUSION': 2,
    'APPLE A11 BIONIC': 3,
    'APPLE A11 BIONIC': 4,
    'APPLE A13 BIONIC': 5,
    'APPLE A14 BIONIC': 6,
    'APPLE A14 BIONIC': 7,
    'APPLE A15 BIONIC': 8,
    'APPLE A16 BIONIC': 9,
    'APPLE A17 BIONIC': 10
}

KAMERA_SCALE = {
    '8 MP(BELAKANG) & 1.2 MP(DEPAN)': 1,
    '12 MP(BELAKANG) & 7 MP(DEPAN)': 2,
    '12 MP(BELAKANG) & 12 MP(DEPAN)': 3,
    '24 MP(BELAKANG) & 7 MP(DEPAN)': 4,
    '12+12+12 MP(BELAKANG) & 12 MP(DEPAN)': 5,
    '48+12+12 MP(BELAKANG) & 12 MP(DEPAN)': 6,
}
